"""initial schema: plants, devices, energy_readings

Revision ID: c6b8aaf8ed51
Revises: 
Create Date: 2026-05-27 15:21:27.695798
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b8aaf8ed51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.String(length=64), nullable=False),
    sa.Column('device_sn', sa.String(length=64), nullable=False),
    sa.Column('granularity', sa.String(length=8), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('reading_hour', sa.Integer(), nullable=True),
    sa.Column('energy_kwh', sa.Float(), nullable=True),
    sa.Column('peak_power_w', sa.Float(), nullable=True),
    sa.Column('avg_power_w', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'device_sn', 'reading_date', 'granularity', 'reading_hour', name='uq_energy_reading')
    )
    with op.batch_alter_table('energy_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_energy_readings_device_sn'), ['device_sn'], unique=False)
        batch_op.create_index(batch_op.f('ix_energy_readings_granularity'), ['granularity'], unique=False)
        batch_op.create_index(batch_op.f('ix_energy_readings_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_energy_readings_reading_date'), ['reading_date'], unique=False)
        batch_op.create_index('ix_energy_sn_gran_date', ['device_sn', 'granularity', 'reading_date'], unique=False)

    op.create_table('plants',
    sa.Column('plant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('server', sa.String(length=255), nullable=True),
    sa.Column('account', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('plant_id')
    )
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plants_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_plants_name'), ['name'], unique=False)

    op.create_table('devices',
    sa.Column('device_sn', sa.String(length=64), nullable=False),
    sa.Column('plant_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('device_type_name', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.plant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_sn')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_plant_id'), ['plant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_plant_id'))

    op.drop_table('devices')
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plants_name'))
        batch_op.drop_index(batch_op.f('ix_plants_account'))

    op.drop_table('plants')
    with op.batch_alter_table('energy_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_energy_sn_gran_date')
        batch_op.drop_index(batch_op.f('ix_energy_readings_reading_date'))
        batch_op.drop_index(batch_op.f('ix_energy_readings_plant_id'))
        batch_op.drop_index(batch_op.f('ix_energy_readings_granularity'))
        batch_op.drop_index(batch_op.f('ix_energy_readings_device_sn'))

    op.drop_table('energy_readings')
    # ### end Alembic commands ###
